packages/shared/src/utils/contract/trade-url-params-config.ts
packages/shared/src/utils/helpers/active-symbols.ts
packages/shared/src/utils/helpers/start-date.ts
packages/trader/src/App/Components/Elements/market-countdown-timer.tsx
packages/trader/src/AppV2/Components/ContractCard/contract-card.tsx
packages/trader/src/AppV2/Components/FavoriteSymbols/favorite-symbols.tsx
packages/trader/src/AppV2/Components/Guide/__tests__/guide.spec.tsx
packages/trader/src/AppV2/Components/MarketCategory/market-category.tsx
packages/trader/src/AppV2/Components/MarketCategoryItem/market-category-item.tsx
packages/trader/src/AppV2/Components/MarketSelector/market-selector.tsx
packages/trader/src/AppV2/Components/SymbolSearchResults/symbol-search-results.tsx
packages/trader/src/AppV2/Containers/Chart/trade-chart.tsx
packages/trader/src/AppV2/Containers/Trade/__tests__/trade.spec.tsx
packages/trader/src/AppV2/Containers/Trade/trade.tsx
packages/trader/src/AppV2/Hooks/__tests__/useContractsForCompany.spec.tsx
packages/trader/src/AppV2/Hooks/useContractsForCompany.ts
packages/trader/src/AppV2/Hooks/useGetSymbolSearchResults.ts
packages/trader/src/AppV2/Utils/sort-symbols-utils.ts
packages/trader/src/AppV2/Utils/symbol-categories-utils.ts
packages/trader/src/Modules/Contract/Containers/replay-chart.tsx
packages/trader/src/Modules/Trading/Components/Form/ContractType/contract-type-widget.tsx
packages/trader/src/Modules/Trading/Containers/trade-chart.tsx
packages/trader/src/Stores/Modules/Trading/Helpers/contract-type.ts
packages/trader/src/Stores/Modules/Trading/trade-store.ts

Refactor contract handling and symbol display logic

---

.github/workflows/push_and_pull_crowdin_translations.yml

Matin/Commit Translation Workflow

---

.github/workflows/release_production.yml
.github/workflows/release_staging.yml

Adjusting Staging & Prod GH Workflows

Matin/Adjusting Staging & Prod GH Workflows

---

package.json

Matin/Updated Build Scripts Again

---

.github/workflows/generate-ai-dashboard.yml
.github/workflows/track-merged-prs.yml

- Added auto merge ability for dashboard changes
- Fixed creating dashboard PR loop

Prince/ Fix Dashboard Workflow

---

.github/actions/build/action.yml
.github/workflows/release_production.yml
.github/workflows/release_staging.yml
package-lock.json

Temp Excluding Tests From Build

Matin/Temp Excluding Tests From Build

---

.github/workflows/ai-dashboard-unified.yml

Prince/fix: auto merging of AI dashboard PR

---

.github/workflows/ai-dashboard-unified.yml

Prince/chore: debugging auto merge

---

.github/workflows/ai-dashboard-unified.yml

Prince/chore: add force merge for dashboard PR only

---

.github/actions/publish_to_pages_production/action.yml
jest.config.base.js
package-lock.json
package.json

Matin/Corrected CF Branch

---

packages/core/src/App/Components/Layout/Header/toggle-menu-drawer.jsx
packages/reports/src/Stores/Modules/Profit/profit-store.js
packages/shared/src/utils/helpers/active-symbols.ts
packages/trader/src/AppV2/Components/ContractCard/contract-card.tsx
packages/trader/src/AppV2/Components/MarketCategoryItem/market-category-item.tsx
packages/trader/src/AppV2/Components/MarketSelector/market-selector.tsx
packages/trader/src/AppV2/Containers/Trade/trade.tsx
packages/trader/src/AppV2/Hooks/__tests__/useContractsForCompany.spec.tsx
packages/trader/src/AppV2/Hooks/useActiveSymbols.ts
packages/trader/src/AppV2/Hooks/useContractsForCompany.ts
packages/trader/src/AppV2/Hooks/useDefaultSymbol.ts
packages/trader/src/AppV2/Hooks/useGetFavoriteSymbols.ts
packages/trader/src/AppV2/Hooks/useGetSymbolSearchResults.ts
packages/trader/src/AppV2/Utils/closed-market-message-utils.ts
packages/trader/src/Stores/Modules/Trading/Helpers/contract-type.ts
packages/trader/src/Stores/Modules/Trading/trade-store.ts

- feat: integrate responsive view

Akmal / feat: integrate responsive view

---

.github/workflows/ai-code-analysis.yml
.github/workflows/ai-dashboard.yml

Prince/ use reusable AI workflows

---

.github/workflows/ai-dashboard.yml

Prince/ retest dashboard workflow

---

.github/workflows/ai-code-analysis.yml
.github/workflows/ai-dashboard.yml

Prince/update workflow to use official deriv-com reusable workflow

---

packages/shared/src/utils/helpers/active-symbols.ts
packages/trader/src/Stores/Modules/Trading/trade-store.ts

fix: improve market status handling for symbols in TradeStore

Akmal / fix: improve market status handling for symbols in TradeStore

---

packages/components/src/components/contract-card/contract-card.scss
packages/components/src/components/u-i-loader/ui-loader.scss
packages/core/src/App/Components/Layout/Footer/endpoint-note.jsx
packages/shared/src/styles/tokens/components.scss
packages/shared/src/styles/tokens/semantic.scss
packages/trader/src/sass/app/_common/components/market-is-closed-overlay.scss
scripts/generate-colors.js

Fix overlay on contract card closed status in positions drawer
Before:
After:

Nijil / Fix overlay on contract card closed status in positions drawer

---

packages/trader/src/AppV2/Components/EntryExitDetails/entry-exit-details.tsx
packages/trader/src/AppV2/Components/TradeParameters/Duration/duration.tsx
packages/trader/src/AppV2/Utils/trade-params-utils.tsx
packages/trader/src/Modules/Trading/Components/Form/WheelPicker/wheel-picker-mobile.tsx
packages/trader/src/Modules/Trading/Components/Form/WheelPicker/wheel-picker.tsx
packages/trader/src/sass/app/_common/components/range-slider.scss

- fix: End time showing invalid time on responsive
- fix: disabled color in wheel picker
- fix: duration resets after refresh on responsive
- fix: remove border from range slider thumb for improved styling

Akmal / fix: bugs

---

packages/core/src/Stores/portfolio-store.js
packages/trader/src/AppV2/Containers/Chart/trade-chart.tsx
packages/trader/src/Modules/Trading/Containers/trade-chart.tsx

This pull request introduces significant performance and stability improvements to the portfolio and chart components by optimizing how frequently-updating data is handled and by stabilizing prop references to prevent unnecessary rerenders. The changes focus on debouncing updates, using memoization and stable references, and improving MobX state management to reduce UI glitches and improve responsiveness.
**Portfolio update handling improvements:**
- Replaced the use of `lodash.throttle` with `lodash.debounce` for position updates and added a mutex (`isUpdatingPositions`) to prevent concurrent updates, ensuring the `updatePositions` method runs safely and efficiently. The update logic now atomically processes and clears the response queue within a MobX `runInAction` for better state …

Jim/grwt 6886/barrier on the chart glitch

---

packages/trader/src/AppV2/Containers/Trade/trade.tsx
packages/trader/src/AppV2/Utils/__tests__/trade-param-utils.spec.tsx
packages/trader/src/AppV2/Utils/trade-params-utils.tsx
packages/trader/src/Modules/Trading/Components/Form/TradeParams/Duration/duration.tsx
packages/trader/src/Stores/Modules/Trading/__tests__/trade-store.spec.ts
packages/trader/src/Stores/Modules/Trading/trade-store.ts

- fix: higher/lower proposal error in responsive
- fix: vanillas End time UI reset on desktop

Akmal / Fix more bugs

---

package-lock.json
package.json
packages/core/package.json
packages/trader/package.json

This PR updates @deriv-com/derivatives-charts to 1.1.1

Update derivatives-charts to 1.1.1

---

package-lock.json
package.json
packages/core/package.json
packages/trader/package.json

This PR updates @deriv-com/derivatives-charts to 1.1.2

Update derivatives-charts to 1.1.2

---

packages/components/src/components/video-player/video-player.tsx

- fix: add safe hook wrapper for RTL context handling in VideoPlayer

Akmal / fix: add safe hook wrapper for RTL context handling in VideoPlayer

---

package-lock.json
package.json
packages/core/package.json
packages/trader/package.json

This PR updates @deriv-com/derivatives-charts to 1.1.8

Update derivatives-charts to 1.1.8

---

.github/workflows/pr_preview.yml

Trigger Release

---

packages/trader/src/AppV2/Components/TradeParameters/Barrier/barrier-input.tsx

- fix: barrier modal crashing bug

Akmal / fix: barrier modal crashing bug

---

.github/pull_request_template.md
docs/architecture/architecture-analysis.md

Matin/ Updated PR template

---

docs/README.md

- Updated README Links
**Related Issue:** Fixes #(issue)
(Add screenshots if UI changes)
**Before:**
**After:**

Matin/ Updated README Links

---

packages/trader/src/AppV2/Hooks/__tests__/useFetchProposalData.spec.tsx
packages/trader/src/AppV2/Hooks/useActiveSymbols.ts
packages/trader/src/AppV2/Hooks/useDtraderQuery.ts

feat: enhance localStorage management for active symbols and improve cache invalidation

Akmal / feat: enhance localStorage management for active symbols and improve cache invalidation

---

packages/api-v2/src/hooks/index.ts
packages/api-v2/src/hooks/useDebounce.ts
packages/trader/src/AppV2/Components/Guide/__tests__/guide.spec.tsx
packages/trader/src/AppV2/Components/Guide/guide.tsx
packages/trader/src/AppV2/Components/TradeParameters/Barrier/__tests__/barrier-input.spec.tsx
packages/trader/src/AppV2/Components/TradeParameters/Barrier/barrier-input.tsx
packages/trader/src/AppV2/Components/TradeParameters/Barrier/barrier.tsx
packages/trader/src/AppV2/Hooks/useGuideContractTypes.ts
packages/trader/src/Stores/Modules/Trading/__tests__/barrier-reset.spec.ts
packages/trader/src/Stores/Modules/Trading/trade-store.ts

- Replaced useContractsFor hook with useGuideContractTypes in Guide component to prevent unnecessary API calls.
- Updated BarrierInput tests to remove reliance on localStorage and adjusted validation logic.
- Simplified Barrier component by removing localStorage handling and ensuring proper state synchronization.
- Introduced useDebounce hook for better input validation in BarrierInput.
- Enhanced TradeStore to prevent clearing barriers for markets that require them, ensuring better UX.
(Brief description of what this PR does)
**Related Issue:** Fixes #(issue)
(Add screenshots if UI changes)
**Before:**
**After:**

Akmal / feat: barrier components for improved contract handling
